# Generated by Django 5.2.3 on 2025-06-19 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "company_logo",
                    models.ImageField(blank=True, null=True, upload_to="logos/"),
                ),
                (
                    "issue_size",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("price_band", models.CharField(max_length=50)),
                ("open_date", models.DateField()),
                ("close_date", models.DateField()),
                ("listing_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("listed", "Listed"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                (
                    "rhp_document",
                    models.FileField(blank=True, null=True, upload_to="documents/rhp/"),
                ),
                (
                    "drhp_document",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/drhp/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "lot_size",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "IPO",
                "verbose_name_plural": "IPOs",
                "ordering": ["-created_at"],
            },
        ),
    ]
